FROM ghcr.io/make87/cuda:12.4.1-cudnn-runtime-ubuntu22.04

RUN apt-get update \
    && apt-get install -y \
      build-essential \
      cmake \
      nasm \
      curl \
      jq \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
ENV PATH="/root/.cargo/bin:${PATH}"

# Set PATH after installation
ENV PATH="/usr/local/rustup/bin:/usr/local/cargo/bin:${PATH}"
# Create a profile script to export PATH
RUN echo 'export PATH="/usr/local/rustup/bin:/usr/local/cargo/bin:${PATH}"' > /etc/profile.d/rust.sh
# Symlink cargo and rustup to /usr/local/bin
RUN ln -s /usr/local/cargo/bin/cargo /usr/local/bin/cargo \
    && ln -s /usr/local/cargo/bin/rustup /usr/local/bin/rustup

# Ensure Rust Analyzer is installed via rustup
RUN rustup component add rust-analyzer
# Copy the startup script
COPY entrypoint-dev.sh /entrypoint-dev.sh
RUN chmod +x /entrypoint-dev.sh

# Set the default command to execute the startup script
ENTRYPOINT ["/entrypoint-dev.sh", "/home/state/code"]