FROM ghcr.io/make87/rust:1-bookworm AS build-rust-base-image

# Set PATH after installation
ENV PATH="/usr/local/rustup/bin:/usr/local/cargo/bin:${PATH}"
# Create a profile script to export PATH
RUN echo 'export PATH="/usr/local/rustup/bin:/usr/local/cargo/bin:${PATH}"' > /etc/profile.d/rust.sh
# Symlink cargo and rustup to /usr/local/bin
RUN ln -s /usr/local/cargo/bin/cargo /usr/local/bin/cargo \
    && ln -s /usr/local/cargo/bin/rustup /usr/local/bin/rustup

# Ensure Rust Analyzer is installed via rustup
RUN rustup component add rust-analyzer

RUN apt-get update \
    && apt install --no-install-suggests --no-install-recommends -y \
        build-essential \
        cmake \
        nasm \
        git

# Copy the startup script
COPY entrypoint-dev.sh /entrypoint-dev.sh
RUN chmod +x /entrypoint-dev.sh

# Set the default command to execute the startup script
ENTRYPOINT ["/entrypoint-dev.sh", "/home/state/code"]