FROM ghcr.io/make87/debian:bookworm AS base-image

ARG VIRTUAL_ENV=/make87/venv

RUN apt-get update \
    && apt-get install --no-install-suggests --no-install-recommends -y \
        build-essential \
        python3-pip \
        python3 \
        libpython3-dev \
        python3-venv \
        git \
        sudo \
        libatomic1 \
        wget \
    && python3 -m venv ${VIRTUAL_ENV} \
    && ${VIRTUAL_ENV}/bin/pip install --upgrade pip setuptools wheel \
    && ${VIRTUAL_ENV}/bin/pip install uv \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Copy the startup script
COPY entrypoint-dev.sh /entrypoint-dev.sh
RUN chmod +x /entrypoint-dev.sh

# Set the default command to execute the startup script
ENTRYPOINT ["/entrypoint-dev.sh", "/home/state/code"]